#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('net.connman', '/'),
					'net.connman.Manager')

technologies = manager.GetTechnologies()

for entry in technologies:
	path = entry[0]
	properties = entry[1]

	if 'p2p' in path:
		for key in properties.keys():
			if key in ["Powered"]:
				val = int(properties[key])
				print "%s = %s" % (key, val)
				if (val == 1):
					print "P2P is Enabled .. Yeah...!!"
				else:
					print "P2P is Disabled -- Please enable it first"

